export default function page() {
    return (
        <main>
            <p>hhhhhh</p>
            <p>dddddd</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
            <p>hhhhhh</p>
        </main>
    )
}